Added check job before installation of PNPM dependencies

diff --git a/.github/workflows/quality-assurance.yml b/.github/workflows/quality-assurance.yml
--- a/.github/workflows/quality-assurance.yml
+++ b/.github/workflows/quality-assurance.yml
@@ -43,7 +43,7 @@ jobs:
               uses: actions/setup-node@v4
               with: 
                 node-version: 20.11
-                
+
             - name: Enable & Prepare PNPM
               run: |
                 corepack enable
@@ -52,6 +52,12 @@ jobs:
             - name: Install PNPM globally as Fallback
               if: failure()
               run: npm install -g pnpm@8.15.5
+            
+            - name: NPM Package File & PNPM Lock File Checks
+              run: |
+                test -f package.json && echo "package.json found" || (echo "package.json missing!" && exit 1)
+                test -f pnpm-lock.yaml && echo "pnpm-lock.yaml found" || (echo "pnpm-lock.yaml missing!" && exit 1)
+              working-directory: web 
 
             - name: Install PNPM dependencies
               run: pnpm install --frozen-lockfile
